### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_serialized')

### ISSUE THREAD

**Issue by Gethin0321** [wppconnect-team/wa-js#1090]
let chat_id = "91xxxxxx@c.us";
const result = await client.pupPage.evaluate(
                        (chat_id) => WPP.chat.getMessages(chat_id, {
                            count: 20
                        }),
                        chat_id
                    );

got:

 Evaluation failed: TypeError: Cannot read properties of undefined (reading '_serialized')
    at t.createWidFromWidLike (https://web.whatsapp.com/app.d38ba36ba32224f079bb.js:85:250389)
    at Function.from (https://web.whatsapp.com/app.d38ba36ba32224f079bb.js:51:212944)
    at Function.fromString (https://web.whatsapp.com/app.d38ba36ba32224f079bb.js:51:212785)
    at /opt/wa-control/src/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:140624
    at Array.map (<anonymous>)
    at Object.t.getMessageById (/opt/wa-control/src/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:140607)
    at __puppeteer_evaluation_script__:1:27
    at ExecutionContext._evaluateInternal (/opt/wa-control/src/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/opt/wa-control/src/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async /opt/wa-control/src/index.js:1053:36

using version: ^2.24.0

**Comment by Gethin0321** [comment]
My fault
