### ISSUE TITLE
WhatsApp WEB loading error, chat screen turns white after you click

### ISSUE THREAD

**Issue by eduardoff19** [wppconnect-team/wa-js#1249]
![whatsapp-web](https://github.com/wppconnect-team/wa-js/assets/42363005/1287b1ce-d171-42d2-8c47-0ba37760f9a2)
![Uploading problema carregamento pagina whatsapp web.png…]()

## Description

I have problem using project: wa-js

After starting the project: npm run launch:local loads the browser and after the WhatsApp WEB conversation page loading action and everything loaded, sometimes you click on any conversation or on the screen, the screen is completely white, gray ( the background screen stays and without being able to click on anything), I always have to press f5, but sometimes it doesn't work, this has been happening for about 20 days, and I'm always updating the build javascript files also download whatsapp javascript and running npm run launch:local, spawning new wppconnect-wa.js - but the problem is reoccurring frequently.

it resolves for a few days and then comes back, it's an intermittent problem, and I've tested it on several accounts, are any of you experiencing this?

## Environment

- **WhatsApp version:**  2.2331.7
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome XX / Chromium XX
- **OS:** Windows X / OSX X.Y.Z
- **MultiDevice (BETA):** yes/no

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
app.8cc58f12b2a1cf6a6be5.js:51 
        
        
       POST https://crashlogs.whatsapp.net/wa_fls_upload_check?type=crashlog&access_token=1063127757113399%7C745146ffa34413f9dbb5469f5370b7af net::ERR_FAILED
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
Promise.then (async)
t @ vendor1~app.be50aaad33253076fc3f.js:4136
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
U @ app.8cc58f12b2a1cf6a6be5.js:51
k @ app.8cc58f12b2a1cf6a6be5.js:51
y @ vendor1~app.be50aaad33253076fc3f.js:16397
b @ vendor1~app.be50aaad33253076fc3f.js:16400
S @ vendor1~app.be50aaad33253076fc3f.js:16424
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
Promise.then (async)
t @ vendor1~app.be50aaad33253076fc3f.js:4136
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
w @ app.8cc58f12b2a1cf6a6be5.js:51
D @ app.8cc58f12b2a1cf6a6be5.js:51
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
F @ app.8cc58f12b2a1cf6a6be5.js:51
t.sendLogs @ app.8cc58f12b2a1cf6a6be5.js:51
(anonymous) @ main.59eb9d8db4c0ea79c5cd.js:6
(anonymous) @ main.59eb9d8db4c0ea79c5cd.js:6
Promise.then (async)
c @ main.59eb9d8db4c0ea79c5cd.js:6
(anonymous) @ main.59eb9d8db4c0ea79c5cd.js:6
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
Promise.then (async)
t @ vendor1~app.be50aaad33253076fc3f.js:4136
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
U @ main.59eb9d8db4c0ea79c5cd.js:6
t.default @ main.59eb9d8db4c0ea79c5cd.js:6
t.default @ main.59eb9d8db4c0ea79c5cd.js:6
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:93
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
app.8cc58f12b2a1cf6a6be5.js:55 
        
        
       GET https://media-gru2-2.cdn.whatsapp.net/v/t62.36145-24/55872319_279773524411073_5139657666292386029_n.enc?ccb=11-4&oh=01_AdQ-RJsmDJB9Liq1xKlD-Y9Igk9k5JRTJ2DsM7LzpaEItg&oe=64BBAB29&hash=-NQ8eYRNqz9F2_j4HqrD2_xfLUhJ-6zi39K4R_Si7k4%3D&_nc_cat=102&mms-type=thumbnail-document&__wa-mms= 403
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:55
m @ app.8cc58f12b2a1cf6a6be5.js:55
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:55
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
t.extendedFetch @ app.8cc58f12b2a1cf6a6be5.js:55
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
g @ app.8cc58f12b2a1cf6a6be5.js:51
url @ app.8cc58f12b2a1cf6a6be5.js:51
t.mms4Download @ app.8cc58f12b2a1cf6a6be5.js:51
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:40
t @ vendor1~app.be50aaad33253076fc3f.js:1964
s @ vendor1~app.be50aaad33253076fc3f.js:1978
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:1983
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:1975
o @ app.8cc58f12b2a1cf6a6be5.js:40
t.default @ app.8cc58f12b2a1cf6a6be5.js:40
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
t @ app.8cc58f12b2a1cf6a6be5.js:40
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:40
t.default @ app.8cc58f12b2a1cf6a6be5.js:40
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
Promise.then (async)
t @ vendor1~app.be50aaad33253076fc3f.js:4136
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:40
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:40
t @ app.8cc58f12b2a1cf6a6be5.js:40
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:40
t.default @ app.8cc58f12b2a1cf6a6be5.js:40
t.backoff @ app.8cc58f12b2a1cf6a6be5.js:40
t.exponentialBackoff @ app.8cc58f12b2a1cf6a6be5.js:40
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
w @ app.8cc58f12b2a1cf6a6be5.js:51
D @ app.8cc58f12b2a1cf6a6be5.js:51
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
R @ app.8cc58f12b2a1cf6a6be5.js:51
download @ app.8cc58f12b2a1cf6a6be5.js:51
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
t @ vendor1~app.be50aaad33253076fc3f.js:4131
s @ vendor1~app.be50aaad33253076fc3f.js:4145
Promise.then (async)
t @ vendor1~app.be50aaad33253076fc3f.js:4136
s @ vendor1~app.be50aaad33253076fc3f.js:4145
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4150
(anonymous) @ vendor1~app.be50aaad33253076fc3f.js:4142
G @ app.8cc58f12b2a1cf6a6be5.js:51
U @ app.8cc58f12b2a1cf6a6be5.js:51
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:51
(anonymous) @ app.8cc58f12b2a1cf6a6be5.js:40
t @ vendor1~app.be50aaad33253076fc3f.js:1964
s @ vendor1~app.be50aaad33253076fc3f.js:1978
vendor1~app.be50aaad33253076fc3f.js:24580 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ml (vendor1~app.be50aaad33253076fc3f.js:27179:21)
    at e (vendor1~app.be50aaad33253076fc3f.js:23963:30)
    at ys (vendor1~app.be50aaad33253076fc3f.js:24654:32)
    at wu (vendor1~app.be50aaad33253076fc3f.js:27390:51)
    at vl (vendor1~app.be50aaad33253076fc3f.js:26712:17)
    at pl (vendor1~app.be50aaad33253076fc3f.js:26706:31)
    at hl (vendor1~app.be50aaad33253076fc3f.js:26697:13)
    at nl (vendor1~app.be50aaad33253076fc3f.js:26485:22)
    at al (vendor1~app.be50aaad33253076fc3f.js:26507:37)
    at Fi (vendor1~app.be50aaad33253076fc3f.js:23252:21)
```

## Additional context / Screenshot
[](url)
[Add any other context about the problem here. If applicable, add screenshots to help explain.](https://i.ibb.co/WDgYcGc/problema-carregamento-pagina-whatsapp-web.png)
![Screenshot_3](https://github.com/wppconnect-team/wa-js/assets/42363005/07a77f7d-c7df-4c15-9aca-9ca0fd636c4e)

https://i.ibb.co/WHxMBWN/Screenshot-3.png

**Comment by yuzedong** [comment]
The issue still persists when I click on a chat conversation window. Please fix it. Thank you very much.

**Comment by yuzedong** [comment]
Could you please tell me if there is any schedule for fixing this bug? Tks!

**Comment by yuzedong** [comment]
It's an intermittent problem,Sometimes it's ok, but if I reload the web.whatsapp.com page some times and click on the chat conversation window again, the issue reappears.
![WX20230804-102503@2x](https://github.com/wppconnect-team/wa-js/assets/6629143/6ed7b6a2-067f-4e9e-aba8-b8d01224cfae)

**Comment by edgardmessias** [comment]
@yuzedong , it's hard this time, I will try to change the webpack loader to avoid this, but the problem is the async file load
