### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'useMsgValues')

### ISSUE THREAD

**Issue by DXPRO** [wppconnect-team/wa-js#1374]
## Description

This error causes all conversations to disappear from the WhatsApp web chat screen

## Environment

- **WhatsApp version:** 2.2340.9
- **WA-JS version(s):** v2.26.1
- **Browser:** Chrome
- **OS:** Windows 11
- **MultiDevice (BETA):** yes

## Steps to Reproduce

To find this possible error, the steps are as follows:

1 - I'm using selenium webdriver to inject wa-js into the browser console after the WhatsApp web page is loaded and in this first step, if the QRcode has already been read, the conversations disappear!

## Log Output

```
https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js 29:71608 TypeError: Cannot read properties of undefined (reading 'useMsgValues')
    at t.default (https://web.whatsapp.com/main.01b1645b7f5da2551104.js:5:1157727)
    at _o (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:30:62964)
    at wu (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:30:120158)
    at vl (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:30:109100)
    at pl (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:30:109028)
    at hl (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:30:108891)
    at nl (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:30:105698)
    at al (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:30:106087)
    at Fi (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:30:46805)
    at https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:30:112479

```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by edgardmessias** [comment]
fixed by https://github.com/wppconnect-team/wa-js/commit/a60bbd3484c86ba8f3b6c4e09e97f6e4d66baf01
