### ISSUE TITLE
Erro ao receber evento de mensagem quoted

### ISSUE THREAD

**Issue by Rubens-Gasparotto** [wppconnect-team/wa-js#2054]
https://github.com/wppconnect-team/wa-js/blob/97c2e3ea5e131f008c715214860103ee00c3b7f1/src/chat/functions/getQuotedMsgKey.ts#L45C7-L45C79

Versão WA-JS: 3.4.1

Ao receber mensagens "quoted", este erro está ocorrendo e o evento de recebimento de mensagem não está sendo disparado.

![image](https://github.com/wppconnect-team/wa-js/assets/54379903/4a785856-03d7-4158-8d37-960c9629837f)

```
JS Stack: TypeError: e.remote.isStatusV3 is not a function
    at t.getMessageById (/home/node/app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:143740)
    at Object.e (/home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:29679)
    at e.next (<anonymous>)
    at X (/home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:29338)
    at a (/home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:29925)
    at /home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:29984
    at new Promise (<anonymous>)
    at Object.$ (/home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:29865)
    at Object.Z [as getMessageById] (/home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:29444)
    at pptr:evaluate;%2Fhome%2Fnode%2Fapp%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:68
    at pptr:evaluate;%2Fhome%2Fnode%2Fapp%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:98
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fhome%2Fnode%2Fapp%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
```

**Comment by jhonnyjks** [comment]
Fix para urgência:

`// Resolvenndo bug 'TypeError: i.Wid.isStatusV3 is not a function'
    if(!WPP.whatsapp.Wid.isStatusV3) {
      WPP.whatsapp.Wid.isStatusV3 = () => false
    }`
