### ISSUE TITLE
Unable to send Text/File Message, Module findChat was not found with e=>e.findChat

### ISSUE THREAD

**Issue by ariona** [wppconnect-team/wa-js#2098]
### WA-JS Version

3.4.2

### WhatsApp Version

2.3000.1014827428

### Browser Version

126.0.6478.127

### Operation System

OS X Sonoma

### Steps to reproduce

1. Send chat with sendTextMessage Method with createChat option to true
2. Send chat with sendFileMessage Method with createChat option to true

### What is expected?

This should send message or media to recipient number

### What is actually happening?

Now it's return error because internal method is not found. Below is the error details:

```
wpp.js:2 Module findChat was not found with e=>e.findChat

Uncaught (in promise) 
  TypeError: (0 , i.findChat) is not a function
      at t.find (core.js:2:141127)
      at t.assertFindChat (core.js:2:100130)
      at t.sendFileMessage (core.js:2:177171)
```

This caused issue with sending message.

**Comment by marcogaruthix** [comment]
Same problem here... I'm unable to open chat with any contact

Input:
WPP.chat.openChatBottom('553491929394@c.us');

Output:
Uncaught TypeError: (0 , i.findChat) is not a function
    at t.find (<anonymous>:2:141119)
    at t.assertFindChat (<anonymous>:2:100122)
    at t.openChatBottom (<anonymous>:2:160631)
    at <anonymous>:1:16

**Comment by yuzedong** [comment]
The same issue is causing my application to completely fail to work. If possible, please urgently fix this. Tks very much.

**Comment by issacwillianDEV** [comment]
Here is also giving this error please if you can fix it I would appreciate it

**Comment by bracketsApps007** [comment]
![image](https://github.com/user-attachments/assets/89f5b614-87aa-4b33-9236-e95cc59e159c)

**Comment by ariona** [comment]
There seems to be an issue when using `sendTextMessage`/`sendFileMessage` with `createChat` option set to `true`.
```js
await WPP.chat.sendTextMessage('6281XXXXX0779@c.us', 'Content', { createChat: true })
```

**Comment by sergey-chechaev** [comment]
The same problem

![image](https://github.com/user-attachments/assets/fc8a5e43-1122-443c-a071-7c7a29ed2666)

**Comment by ariona** [comment]
> @sergey-chechaev, ⭐3 XP earned, 🏆First Comment Added completed! Contribute more to raise your XP/Level, complete challenges for extra achievements! [[Sign up for personal dashboard](https://app.devactivity.com/login)]
> 
> ![icon](https://camo.githubusercontent.com/4d5ae52d26d58ab8d1bfcb576b86726d103a94c7640f0cc528df97bcfc132cf9/68747470733a2f2f656d6265646461626c65732e64657661637469766974792e636f6d2f62616467652d6669727374436f6d6d656e7441646465642d313731333334363031343235352e737667)

This bot should be turned off

**Comment by Parveen-Mothsara** [comment]
await WPP.chat.sendTextMessage('9199XXXXX0779@c.us', 'Content', { createChat: true })

this is giving same error please resolve...

**Comment by Shibubx** [comment]
well.. I have all the issues above

**Comment by ariona** [comment]
I think WhatsApp update/move some of their code..
This issue caused by `findChat` module which is missing.

https://github.com/wppconnect-team/wa-js/blob/cb06285757250cdabbdaf4535dcf97bdcdd509ef/src/whatsapp/functions/findChat.ts

**Comment by Shibubx** [comment]
> I think WhatsApp update/move some of their code.. This issue caused by `findChat` module which is missing.
> 
> https://github.com/wppconnect-team/wa-js/blob/cb06285757250cdabbdaf4535dcf97bdcdd509ef/src/whatsapp/functions/findChat.ts

solution ? 
alternative

**Comment by Shibubx** [comment]
I think this is the end
now they encoded the chat ID keeps changing ..

**Comment by sergey-chechaev** [comment]
> I think this is the end now they encoded the chat ID keeps changing ..

This method still working `https://web.whatsapp.com/send?phone=7926xxxxxxx ` so it means that you can find chat

**Comment by Shibubx** [comment]
> > I think this is the end now they encoded the chat ID keeps changing ..
> 
> This method still working `https://web.whatsapp.com/send?phone=7926xxxxxxx ` so it means that you can find chat

no try https //api.whatsapp.com/send phone=number' see what it says

**Comment by ariona** [comment]
I can confirm The update is working, Thanks @icleitoncosta

**Comment by yuzedong** [comment]
very well. Thanks.

**Comment by icleitoncosta** [comment]
You're welcome, hugs

**Comment by Parveen-Mothsara** [comment]
Its working now Thanks all.

**Comment by jhowbhz** [comment]
Thank you
