### ISSUE TITLE
Error: wid error: invalid wid: 6@c.us

### ISSUE THREAD

**Issue by rhutikcodes** [wppconnect-team/wa-js#426]
Unable to send messages getting this error

Uncaught (in promise) Error: wid error: invalid wid: 6@c.us
    at new l (bootstrap_qr.a93ca7c63be0f2cdef56.js:71:24606)
    at s (bootstrap_qr.a93ca7c63be0f2cdef56.js:71:28948)
    at Object.d [as createUserWid] (bootstrap_qr.a93ca7c63be0f2cdef56.js:71:29303)
    at t.createWid (wp.js:2:182784)
    at t.assertWid (wp.js:2:88293)
    at t.prepareRawMessage (wp.js:2:120566)
    at t.sendRawMessage (wp.js:2:126923)
    at Object.t.sendTextMessage (wp.js:2:128197)

**Comment by rhutikcodes** [comment]
#427  solved the problem

**Comment by rhutikcodes** [comment]
#427 solved the problem
