### ISSUE TITLE
Not able to open whatsapp web

### ISSUE THREAD

**Issue by rhutikcodes** [wppconnect-team/wa-js#741]
## Description

Not able to open whatsapp web, I am trying to run the project on my local machine

## Environment

- **WhatsApp version:** 2.2241.7
- **WA-JS version(s):** 2.15.0
- **Browser:** 07.0.5304.18 
- **OS:** Mac OS Ventura 13
- 
## Steps to Reproduce

1. npm run launch:local 

## Log Output

```
serviceworker.js:1 Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
    at serviceworker.js:1:47881
    at Generator.next (<anonymous>)
    at t (serviceworker.js:1:32220)
    at c (serviceworker.js:1:32431)
(anonymous) @ serviceworker.js:1
t @ serviceworker.js:1
c @ serviceworker.js:1
vendor1~bootstrap_qr.b9c8527c02346d561658.js:27 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Hu (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:107119)
    at vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:55536
    at Ua (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:67123)
    at Ws (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:114332)
    at Tu (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:98520)
    at ku (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:98448)
    at Eu (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:98311)
    at vu (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:95298)
    at fu (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:92646)
    at Zu (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:108772)
ss @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
n.payload @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
co @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
Va @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
Ws @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
Tu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
ku @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
Eu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
vu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
fu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
Zu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
(anonymous) @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
yu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
rl @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
t.render @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
(anonymous) @ bootstrap_qr.3bfad085c8a35574c4db.js:71
t @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:2
s @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:2
H @ bootstrap_qr.3bfad085c8a35574c4db.js:40
B @ bootstrap_qr.3bfad085c8a35574c4db.js:40
vendor1~bootstrap_qr.b9c8527c02346d561658.js:27 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Hu (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:107119)
    at d (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:52739)
    at m (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:54009)
    at vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:56086
    at Ua (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:67123)
    at Ws (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:113120)
    at Tu (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:98520)
    at ku (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:98448)
    at Eu (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:98311)
    at vu (vendor1~bootstrap_qr.b9c8527c02346d561658.js:27:95298)
ss @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
n.payload @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
co @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
Va @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
Ws @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
Tu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
ku @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
Eu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
vu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
fu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
Zu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
(anonymous) @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
yu @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
rl @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
t.render @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:27
(anonymous) @ bootstrap_qr.3bfad085c8a35574c4db.js:71
t @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:2
s @ vendor1~bootstrap_qr.b9c8527c02346d561658.js:2
H @ bootstrap_qr.3bfad085c8a35574c4db.js:40
B @ bootstrap_qr.3bfad085c8a35574c4db.js:40
2serviceworker.js:1 Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
    at serviceworker.js:1:47881
    at Generator.next (<anonymous>)
    at t (serviceworker.js:1:32220)
    at c (serviceworker.js:1:32431)
```

**Comment by danieldocki** [comment]
![Screenshot 2022-11-09 at 19 18 40](https://user-images.githubusercontent.com/10542/200954139-1342be65-f9ad-4593-a7a7-2a7b4c37299d.png)

**Comment by rhutikcodes** [comment]
Same here @edgardmessias 

For now, I have added a delay before injecting wppconnect-wa.js file

**Comment by edgardmessias** [comment]
Thanks guys, now I am going to check what I can do to avoid it.
