### ISSUE TITLE
Erro ao criar uma etiqueta, podem me ajudar?

### ISSUE THREAD

**Issue by higormachado3** [wppconnect-team/wa-js#799]
Uncaught (in promise) Error: This call is only supported in non-MD mode
    at E.getNewLabelColor (app.cbe2fde94befbde07514.js:75:499960)
    at t.getNewLabelColor (wpp.js:2:217571)
    at t.addNewLabel (wpp.js:2:214844)
    at salvarEtiqueta (campaign_back.js:464:31)

Aparece esse erro no console, e se eu colocar em modo MD da outro erro, e possivel fazer essa função funcionar? se sim como?

**Comment by edgardmessias** [comment]
Como o próprio erro diz, infelizmente era possível criar etiqueta no modo antigo do WhatsApp, agora que ficou padrão o multi-device, não é mais possível
