### ISSUE TITLE
Crash of Protocol-Log

### ISSUE THREAD

**Issue by genseric** [wppconnect-team/wa-js#807]
## Description

When the npm run launch:protocol-log is launched, crashes with WPP is not defined. 
And If i add window.WPP to the code, it crashes with 
```
page.evaluate: TypeError: Cannot read properties of null (reading 'sendIq')
    at eval (eval at evaluate (:191:30), <anonymous>:3:35)
    at UtilityScript.evaluate (<anonymous>:193:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at Page.<anonymous> (/Users/XXX/Documents/GitHub/wa-js/src/tools/launchProtocolLog.ts:63:10)

```

## Environment

- **WhatsApp version:** 2.2246.10
- **WA-JS version(s):** v2.17.0
- **Browser:** Chromium 
- **OS:** Mac OS 13
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. npm run launch:protocol-log

## Log Output

```

page.waitForFunction: ReferenceError: WPP is not defined
    at eval (eval at predicate (eval at evaluate (:191:30)), <anonymous>:1:7)
    at predicate (eval at evaluate (:191:30), <anonymous>:10:20)
    at eval (eval at evaluate (:191:30), <anonymous>:19:82)
    at next (<anonymous>:4563:27)
    at <anonymous>:4573:7
    at Object.run (<anonymous>:4617:22)
    at eval (eval at evaluate (:191:30), <anonymous>:1:14)
    at UtilityScript.evaluate (<anonymous>:193:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
=========================== logs ===========================
  WPP is not defined
============================================================
    at Page.<anonymous> (/Users/XXX/Documents/GitHub/wa-js/src/tools/launchProtocolLog.ts:59:16)

```

**Comment by edgardmessias** [comment]
Hi @genseric , thanks for the report, I will check it later, this part of code is outdated
